# Para ayudar al asesoramiento de este proyecto y por tanto a su realización, estas son las plataformas desde las que se puede dar apoyo

custom: ["https://www.paypal.com/donate/?hosted_button_id=R56WYQP9LUCRA"]
